include:
    - height
shared:
    - svPoint_settings.yml
    - svLine_settings.yml
    - svFilter_settings.yml
    - svJunction_settings.yml
    - ../junction_settings.yml    
    - svSummarize_settings.yml
